trigger:
- main

variables:
  # Запазваме твоите оригинални данни за ACR
  dockerRegistryServiceConnection: '823b0184-b606-427f-993a-f325de6efe0c'
  imageRepository: 'ahmedosmangsspringbootdocker'
  containerRegistry: 'aosman.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/complete/Dockerfile'
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    
    # СТЪПКА 1: Компилиране на Java приложението
    - task: Maven@4
      displayName: 'Maven Build'
      inputs:
        # Увери се, че пътят до pom.xml е правилен!
        mavenPomFile: 'complete/pom.xml' 
        goals: 'package'
        jdkVersionOption: '1.11' # Или твоята версия на Java

    # СТЪПКА 2: Docker Build & Push
    # Вече в папката target/ има .war файл, който Docker ще вземе
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest